## **Practical No. 1**
Aim: Implementation of Single Perceptron and Creation of Logic Gates.




Name: Sanika Bhave

Roll no: 10

Batch: D3

#### Single Perceptron Implementation

In [3]:
#Single Perceptron Implementation

In [4]:
#inputs
x_input=[0.1,0.2,0.3]
w_weight=[0.1,0.9,0.5]
threshold=0.2

In [5]:
#activation function
def step(weighted_sum):
    if weighted_sum >= threshold:
        return 1
    else:
        return 0

In [6]:
#calculation of the perceptron
def perceptron():
    weighted_sum=0
    for x,w in zip(x_input,w_weight):
        weighted_sum +=x*w
        print(weighted_sum)
    return step(weighted_sum)

In [7]:
output=perceptron()
print("output=",output)
#output

0.010000000000000002
0.19000000000000003
0.34
output= 1


#### Creation of Logic Gates

In [9]:
#And gate
x1_input=[0,0,1,1]
x2_input=[0,1,0,1]
weight=[1,1,1,1]
bias=1

In [10]:
s=0
x_sum=[]
for x1,x2 in zip(x1_input,x2_input):
  s=x1+x2
  x_sum.append(s)
print(x_sum)

[0, 1, 1, 2]


In [11]:
def perceptron():
    result=[]
    for x,w in zip(x_sum,weight):
        weighted_sum=0
        weighted_sum =weighted_sum + x*w+bias
        result.append(weighted_sum)
    return step(result)

In [12]:
output=[]
def step(result):
  for i in result:
    if i >= 3:
        output.append(1)
    else:
        output.append(0)
  return output

In [13]:
x=perceptron()
print(x)

[0, 0, 0, 1]


In [14]:
#OR gate
output=[]
def step(result):
  for i in result:
    if i >= 2:
        output.append(1)
    else:
        output.append(0)
  return output

In [15]:
x=perceptron()
print(x)

[0, 1, 1, 1]


In [38]:
import numpy as np

def perceptron_not_gate(input):
    weight = -1
    weighted_sum = input * weight
    output = 1 if weighted_sum < 0 else 0
    return output

# Input
input = np.array([0, 1])

print("Testing NOT gate without bias:")
for value in input:
    prediction = perceptron_not_gate(value)
    print(f"Input: {value}, Predicted Output: {prediction}")


Testing NOT gate without bias:
Input: 0, Predicted Output: 0
Input: 1, Predicted Output: 1


In [21]:
#NOR Gate
import numpy as np

def perceptron_nor_gate(inputs):
    weights = np.array([0.5, 0.5])
    weighted_sum = np.dot(inputs, weights)
    output = 1 if weighted_sum <= 0 else 0
    return output

#input
input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

print("Testing NOR gate without bias:")
for input_set in input:
    prediction = perceptron_nor_gate(input_set)
    print(f"Input: {input_set}, Predicted Output: {prediction}")

Testing NOR gate without bias:
Input: [0 0], Predicted Output: 1
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 0


In [23]:
#NAND Gate

def perceptron_nand_gate(inputs):
    weights = np.array([0.5, 0.5])
    weighted_sum = np.dot(inputs, weights)
    output = 1 if weighted_sum <1 else 0
    return output

inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

print("Testing NAND gate without bias:")
for input_set in inputs:
    prediction = perceptron_nand_gate(input_set)
    print(f"Input: {input_set}, Predicted Output: {prediction}")

Testing NAND gate without bias:
Input: [0 0], Predicted Output: 1
Input: [0 1], Predicted Output: 1
Input: [1 0], Predicted Output: 1
Input: [1 1], Predicted Output: 0


#### 1B. Implement Perceptron learning algorithm for classification of following points in to two classes C1,C2


In [25]:
points = {'P0': np.array([-1, -1, -1]), 'P1': np.array([-1, -1, 1]), 'P2': np.array([-1, 1, -1]),
          'P3':np.array([-1, 1, 1]), 'P4': np.array([1, -1, -1]), 'P5': np.array([1, -1, 1]),
          'P6': np.array([1, 1, -1]), 'P7': np.array([1, 1, 1])}

In [26]:
C1 = ['P7']
C2 =['P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6']

weights = np.zeros(len(points['P0']))
bias = 0
print(weights)

[0. 0. 0.]


In [27]:
learning_rate = 1
epochs = 1000

In [28]:
for epoch in range(epochs):
    for point in C2:
        x = points[point]
        y = 1

        summation = np.dot(weights, x) + bias

        if summation<=0:
            weights += learning_rate * x
            bias += learning_rate

In [31]:
print(weights)
print(bias)

[-1. -1. -1.]
3


In [32]:
new_point = np.array([1, 1, 1])
summation = np.dot(weights, new_point) + bias

In [33]:
if(summation>0):
    print(f'The new point {new_point} belongs to class C2')
else:
     print(f'The new point {new_point} belongs to class C1')

The new point [1 1 1] belongs to class C1


In [34]:
new_point = np.array([1, -1, 1])
summation = np.dot(weights, new_point) + bias

In [35]:
if(summation>0):
    print(f'The new point {new_point} belongs to class C2')
else:
     print(f'The new point {new_point} belongs to class C1')

The new point [ 1 -1  1] belongs to class C2


#### 1C.Write a python program to find the number of linearly separable problems

In [36]:
def is_linearly_separable(points1):
    labels = [1, 1, 1, 1, -1, -1, -1, -1]
    weights = np.zeros(len(points1[0]))
    print(weights)

    for _ in range(1000):
        misclassified = False

        for i, point in enumerate(points1):
            if np.dot(point, weights) * labels[i] <= 0:
                weights += labels[i] * point
                misclassified = True
                print(weights)

        if not misclassified:
            return True

points1 = [np.array([-1, -1, -1]), np.array([-1, -1, 1]), np.array([-1, 1, -1]),
           np.array([-1, 1, 1]), np.array([1, -1, -1]), np.array([1, -1, 1]),
          np.array([1, 1, -1]), np.array([1, 1, 1])]

if is_linearly_separable(points1):
    print("The binary classification problem is linearly separable.")
else:
    print("The binary classification problem is not linearly separable.")


[0. 0. 0.]
[-1. -1. -1.]
[-2.  0.  0.]
The binary classification problem is linearly separable.


#### Conclusion: Learned to implement Single Perceptron and Creation of Logic Gates.